### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/firefly-torch#2]
- [ ] add the proposed gender-based firefly algorithm in a separate file
- [ ] try the queen bee breeding methodology
- [ ] try species / colonies that uses either particle swarm updates or genetic algorithms (not both) and have periodic shuffling of fireflies between them
- [ ] try a cosine schedule for the exploration factor, for better simulated annealing
